# Generated by Django 5.0.6 on 2024-06-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("company_name", models.CharField(max_length=255)),
                ("sector", models.CharField(max_length=255)),
                ("market_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "fifty_two_week_high",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "fifty_two_week_low",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
