# Generated by Django 5.0.6 on 2024-06-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="ticker",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
