# Generated by Django 5.0.6 on 2024-07-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0002_alter_stock_ticker"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="average_volume",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="beta",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="current_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="dividend_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="dividend_yield",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="earnings_growth",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="ebitda",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="ebitda_margins",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="enterprise_value",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="gross_margins",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="market_cap",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="net_income",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="operating_margins",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="payout_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="pb_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="pe_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="ps_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="quick_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="revenue_growth",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="roa",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="roe",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="total_debt",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="total_revenue",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
